name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://npm.pkg.github.com
    - run: npm i
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_AUTH_TOKEN}}
